var data = {
  product: {
    Fresh_Kisses: {
      productName: "Fresh Kisses",
      price: 20.0,
      currency: "USD",
      formattedPrice: "$20.00",
      primaryCategory: "CAT",
      imageURL: "images/item9.jpg",
    },
    Butcher_Junior: {
      productName: "Butcher's Junior",
      price: 10.0,
      currency: "USD",
      formattedPrice: "$10.00",
      primaryCategory: "CAT",
      imageURL: "images/item12.jpg",
    },
    Winlary: {
      productName: "Winlary",
      price: 7.0,
      currency: "USD",
      formattedPrice: "$7.00",
      primaryCategory: "CAT",
      imageURL: "images/item16.jpg",
    },
    Bug_Bites: {
      productName: "Bug Bites",
      price: 10.0,
      currency: "USD",
      formattedPrice: "$10.00",
      primaryCategory: "FISH",
      imageURL: "images/item17.jpg",
    },
    Fluval_Betta_Formula: {
      productName: "Fluval Betta Formula",
      price: 9.0,
      currency: "USD",
      formattedPrice: "$9.00",
      primaryCategory: "Fish",
      imageURL: "images/item18.jpg",
    },
    Butcher: {
      productName: "Butcher's",
      price: 9.0,
      currency: "USD",
      formattedPrice: "$9.00",
      primaryCategory: "DOG",
      imageURL: "images/item10.jpg",
    },
    Pulsitos: {
      productName: "Pulsitos",
      price: 18.0,
      currency: "USD",
      formattedPrice: "$18.00",
      primaryCategory: "DOG",
      imageURL: "images/item11.jpg",
    },
    Butcher_Treats: {
      productName: "Butcher's Treats",
      price: 25.0,
      currency: "USD",
      formattedPrice: "$25.00",
      primaryCategory: "DOG",
      imageURL: "images/item15.jpg",
    },
    Chicken_Treats: {
      productName: "Chicken Treats",
      price: 13.0,
      currency: "USD",
      formattedPrice: "$13.00",
      primaryCategory: "BIRD",
      imageURL: "images/item13.jpg",
    },
    Love_Corn: {
      productName: "Love Corn",
      price: 20.0,
      currency: "USD",
      formattedPrice: "$20.00",
      primaryCategory: "BIRD",
      imageURL: "images/item14.jpg",
    },
  },
  cart: {
    //dictionary --> itemId : productId
  },
  cartTotal: 0,
};
